export const countries = [
    { name: 'Afghanistan', code: 'AF', dialCode: '93', mask: 'XXX-XXXXXXX' },
    { name: 'Albania', code: 'AL', dialCode: '355', mask: 'XX XXX XXXX' },
    { name: 'Algeria', code: 'DZ', dialCode: '213', mask: 'XXX XX-XX-XX' },
    { name: 'Andorra', code: 'AD', dialCode: '376', mask: 'XXX XXX' },
    { name: 'Angola', code: 'AO', dialCode: '244', mask: 'XXX XXX XXX' },
    { name: 'Argentina', code: 'AR', dialCode: '54',  mask: 'XX XXXX-XXXX' },
    { name: 'Armenia', code: 'AM', dialCode: '374',  mask: 'XX XXXXXX' },
    { name: 'Australia', code: 'AU', dialCode: '61',  mask: 'XXXX XXX XXX' },
    { name: 'Austria', code: 'AT', dialCode: '43',  mask: 'XXXX XXXXXX' },
    { name: 'Azerbaijan', code: 'AZ', dialCode: '994', mask: 'XX XXX XX XX' },
    { name: 'Bahamas', code: 'BS', dialCode: '1',  mask: '(XXX) XXX-XXXX' },
    { name: 'Bahrain', code: 'BH', dialCode: '973',  mask: 'XXXX XXXX' },
    { name: 'Bangladesh', code: 'BD', dialCode: '880',  mask: 'XXX-XXXXXXX' },
    { name: 'Belarus', code: 'BY', dialCode: '375',  mask: 'XX XXXX-XX-XX' },
    { name: 'Belgium', code: 'BE', dialCode: '32',  mask: 'XXX XX XX XX' },
    { name: 'Brazil', code: 'BR', dialCode: '55',  mask: '(XX) XXXXX-XXXX' },
    { name: 'Canada', code: 'CA', dialCode: '1',  mask: '(XXX) XXX-XXXX' },
    { name: 'China', code: 'CN', dialCode: '86',  mask: 'XXX XXXX XXXX' },
    { name: 'Denmark', code: 'DK', dialCode: '45',  mask: 'XX XX XX XX' },
    { name: 'Egypt', code: 'EG', dialCode: '20',  mask: 'XX XXXX XXXX' },
    { name: 'France', code: 'FR', dialCode: '33',  mask: 'X XX XX XX XX' },
    { name: 'Germany', code: 'DE', dialCode: '49',  mask: 'XXXX XXXXXXX' },
    { name: 'India', code: 'IN', dialCode: '91',  mask: 'XXXXX-XXXXX' },
    { name: 'Indonesia', code: 'ID', dialCode: '62',  mask: 'XXXX-XXXX-XXXX' },
    { name: 'Italy', code: 'IT', dialCode: '39',  mask: 'XXX XXX XXXX' },
    { name: 'Japan', code: 'JP', dialCode: '81',  mask: 'XXX-XXXX-XXXX' },
    { name: 'Mexico', code: 'MX', dialCode: '52',  mask: '(XXX) XXX-XXXX' },
    { name: 'Netherlands', code: 'NL', dialCode: '31',  mask: 'XXXX XXXXXXX' },
    { name: 'New Zealand', code: 'NZ', dialCode: '64',  mask: 'XXX-XXX-XXXX' },
    { name: 'Nigeria', code: 'NG', dialCode: '234',  mask: 'XXX XXX XXXX' },
    { name: 'Pakistan', code: 'PK', dialCode: '92',  mask: 'XXX-XXXXXXX' },
    { name: 'Philippines', code: 'PH', dialCode: '63', mask: 'XXX-XXX-XXXX' },
    { name: 'Poland', code: 'PL', dialCode: '48',  mask: 'XXX XXX XXX' },
    { name: 'Russia', code: 'RU', dialCode: '7',  mask: 'XXX XXX-XX-XX' },
    { name: 'Saudi Arabia', code: 'SA', dialCode: '966',  mask: 'XX XXX XXXX' },
    { name: 'South Africa', code: 'ZA', dialCode: '27',  mask: 'XX XXX XXXX' },
    { name: 'South Korea', code: 'KR', dialCode: '82',  mask: 'XXX-XXXX-XXXX' },
    { name: 'Spain', code: 'ES', dialCode: '34',  mask: 'XXX XXX XXX' },
    { name: 'Sweden', code: 'SE', dialCode: '46',  mask: 'XX-XXX XX XX' },
    { name: 'Switzerland', code: 'CH', dialCode: '41',  mask: 'XX XXX XX XX' },
    { name: 'Thailand', code: 'TH', dialCode: '66',  mask: 'XX XXX XXXX' },
    { name: 'Turkey', code: 'TR', dialCode: '90',  mask: '(XXX) XXX XXXX' },
    { name: 'Ukraine', code: 'UA', dialCode: '380',  mask: 'XX XXX XXXX' },
    { name: 'United Arab Emirates', code: 'AE', dialCode: '971',  mask: 'XX XXX XXXX' },
    { name: 'United Kingdom', code: 'GB', dialCode: '44',  mask: 'XXXXX XXXXXX' },
    { name: 'United States', code: 'US', dialCode: '1',  mask: '(XXX) XXX-XXXX' },
    { name: 'Vietnam', code: 'VN', dialCode: '84',  mask: 'XXX XXXX XXX' },
    { name: 'Zimbabwe', code: 'ZW', dialCode: '263',  mask: 'XX XXX XXXX' }
];

//flags 